name: Code quality

on:
  - push
  - pull_request

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none

      - name: Validate composer.json
        run: composer validate --strict --ansi

      - name: Install composer packages
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 4
          command: composer update --prefer-stable --prefer-dist --no-interaction --no-progress --ansi

      - name: Execute format check
        run: make check

  static-analysis:
    needs: format-check
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none

      - name: Validate composer.json
        run: composer validate --strict --ansi

      - name: Install composer packages
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 4
          command: composer update --prefer-stable --prefer-dist --no-interaction --no-progress --ansi

      - name: Execute static analysis
        run: make static

  unit-tests:
    needs: static-analysis
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: xdebug

      - name: Validate composer.json
        run: composer validate --strict --ansi

      - name: Install composer packages
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 4
          command: composer update --prefer-stable --prefer-dist --no-interaction --no-progress --ansi

      - name: Execute unit tests
        run: make test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: out/testers/coverage.xml
          flags: unittests
